//
//  Localizable.swift
//  MinhaEscolaSP
//
//  Created by Victor Bozelli Alvarez on 21/01/19.
//  Copyright © 2019 PRODESP. All rights reserved.
//

final class Localizable {
    static let aguardandoEnvio = "br.gov.sp.educacao.minhaescola.aguardandoEnvio"
    static let algoDeErradoAconteceu = "br.gov.sp.educacao.minhaescola.algoDeErradoAconteceu"
    static let alterarTelefone = "br.gov.sp.educacao.minhaescola.alterarTelefone"
    static let alunoSemCarteirinha = "br.gov.sp.educacao.minhaescola.alunoSemCarteirinha"
    static let atencao = "br.gov.sp.educacao.minhaescola.atencao"
    static let avaliacaoEnviadaComSucesso = "br.gov.sp.educacao.minhaescola.avaliacaoEnviadaComSucesso"
    static let avaliarUmaVezPorDia = "br.gov.sp.educacao.minhaescola.avaliarUmaVezPorDia"
    static let bibliotecaDeFotos = "br.gov.sp.educacao.minhaescola.bibliotecaDeFotos"
    static let cadastrarTelefone = "br.gov.sp.educacao.minhaescola.cadastrarTelefone"
    static let camera = "br.gov.sp.educacao.minhaescola.camera"
    static let cancelar = "br.gov.sp.educacao.minhaescola.cancelar"
    static let carregando = "br.gov.sp.educacao.minhaescola.carregando"
    static let carregandoBoletim = "br.gov.sp.educacao.minhaescola.carregandoBoletim"
    static let carregandoCalendario = "br.gov.sp.educacao.minhaescola.carregandoCalendario"
    static let carregandoCarteirinha = "br.gov.sp.educacao.minhaescola.carregandoCarteirinha"
    static let carregandoFrequencias = "br.gov.sp.educacao.minhaescola.carregandoFrequencias"
    static let carregandoHorarios = "br.gov.sp.educacao.minhaescola.carregandoHorarios"
    static let carregandoNotas = "br.gov.sp.educacao.minhaescola.carregandoNotas"
    static let comprovanteAnexado = "br.gov.sp.educacao.minhaescola.comprovanteAnexado"
    static let desejaRealizarARematriculaPara = "br.gov.sp.educacao.minhaescola.desejaRealizarARematriculaPara"
    static let digiteEmail = "br.gov.sp.educacao.minhaescola.digiteEmail"
    static let digiteEndereco = "br.gov.sp.educacao.minhaescola.digiteEndereco"
    static let digiteRaCompleto = "br.gov.sp.educacao.minhaescola.digiteRaCompleto"
    static let digiteRgCompleto = "br.gov.sp.educacao.minhaescola.digiteRgCompleto"
    static let digiteRne = "br.gov.sp.educacao.minhaescola.digiteRne"
    static let digiteSenha = "br.gov.sp.educacao.minhaescola.digiteSenha"
    static let documento = "br.gov.sp.educacao.minhaescola.documento"
    static let duvidaAusencias = "br.gov.sp.educacao.minhaescola.duvidaAusencias"
    static let duvidaRa = "br.gov.sp.educacao.minhaescola.duvidaRa"
    static let enviandoAvaliacao = "br.gov.sp.educacao.minhaescola.enviandoAvaliacao"
    static let enviandoInformacoes = "br.gov.sp.educacao.minhaescola.enviandoInformacoes"
    static let enviandoFoto = "br.gov.sp.educacao.minhaescola.enviandoFoto"
    static let erroCalendario = "br.gov.sp.educacao.minhaescola.erroCalendario"
    static let erroGeolocalizacao = "br.gov.sp.educacao.minhaescola.erroGeolocalizacao"
    static let fazendoGeolocalizacao = "br.gov.sp.educacao.minhaescola.fazendoGeolocalizacao"
    static let fazendoLogin = "br.gov.sp.educacao.minhaescola.fazendoLogin"
    static let galeriaDeImagens = "br.gov.sp.educacao.minhaescola.galeriaDeImagens"
    static let imagem = "br.gov.sp.educacao.minhaescola.imagem"
    static let informacoesAtualizadasComSucesso = "br.gov.sp.educacao.minhaescola.informacoesAtualizadasComSucesso"
    static let informacoesComprovante = "br.gov.sp.educacao.minhaescola.informacoesComprovante"
    static let informacoesEnviadasComSucesso = "br.gov.sp.educacao.minhaescola.informacoesEnviadasComSucesso"
    static let iniciar = "br.gov.sp.educacao.minhaescola.iniciar"
    static let internet = "br.gov.sp.educacao.minhaescola.internet"
    static let internetAlimentacao = "br.gov.sp.educacao.minhaescola.internetAlimentacao"
    static let internetBoletim = "br.gov.sp.educacao.minhaescola.internetBoletim"
    static let internetCarteirinha = "br.gov.sp.educacao.minhaescola.internetCarteirinha"
    static let internetFrequencias = "br.gov.sp.educacao.minhaescola.internetFrequencias"
    static let internetHorarioAula = "br.gov.sp.educacao.minhaescola.internetHorarioAula"
    static let internetLogin = "br.gov.sp.educacao.minhaescola.internetLogin"
    static let internetNotas = "br.gov.sp.educacao.minhaescola.internetNotas"
    static let internetSobreMim = "br.gov.sp.educacao.minhaescola.internetSobreMim"
    static let nao = "br.gov.sp.educacao.minhaescola.nao"
    static let naoCadastrado = "br.gov.sp.educacao.minhaescola.naoCadastrado"
    static let naoTenhoInteresse = "br.gov.sp.educacao.minhaescola.naoTenhoInteresse"
    static let necessarioFornecerOComprovanteDeResidencia = "br.gov.sp.educacao.minhaescola.necessarioFornecerOComprovanteDeResidencia"
    static let nenhumaAvaliacaoLancada = "br.gov.sp.educacao.minhaescola.nenhumaAvaliacaoLancada"
    static let ok = "br.gov.sp.educacao.minhaescola.ok"
    static let ops = "br.gov.sp.educacao.minhaescola.ops"
    static let preenchaTodasInformacoes = "br.gov.sp.educacao.minhaescola.preenchaTodasInformacoes"
    static let primeiraSenha = "br.gov.sp.educacao.minhaescola.primeiraSenha"
    static let primeiraSenhaResponavel = "br.gov.sp.educacao.minhaescola.primeiraSenhaResponsavel"
    static let qualOTipoDeArquivoDoComprovante = "br.gov.sp.educacao.minhaescola.qualOTipoDeArquivoDoComprovante"
    static let realizeAMatriculaDe = "br.gov.sp.educacao.minhaescola.realizeAMatriculaDe"
    static let selecioneAOrigemDaFoto = "br.gov.sp.educacao.minhaescola.selecioneAOrigemDaFoto"
    static let selecioneUmAlunoQueNaoRealizouAMatriculaAinda = "br.gov.sp.educacao.minhaescola.selecioneUmAlunoQueNaoRealizouAMatriculaAinda"
    static let semBoletim = "br.gov.sp.educacao.minhaescola.semBoletim"
    static let semEscola = "br.gov.sp.educacao.minhaescola.semEscola"
    static let semFrequenciaTurmaAtual = "br.gov.sp.educacao.minhaescola.semFrequenciaTurmaAtual"
    static let semHorarioTurmaAtual = "br.gov.sp.educacao.minhaescola.semHorarioTurmaAtual"
    static let semNotaTurmaAtual = "br.gov.sp.educacao.minhaescola.semNotaTurmaAtual"
    static let semTurmaAnoAtual = "br.gov.sp.educacao.minhaescola.semTurmaAnoAtual"
    static let semTurmas = "br.gov.sp.educacao.minhaescola.semTurmas";
    static let sim = "br.gov.sp.educacao.minhaescola.sim"
    static let sucesso = "br.gov.sp.educacao.minhaescola.sucesso"
    static let textoCompartilhar = "br.gov.sp.educacao.minhaescola.textoCompartilhar"
    static let tituloCompartilhar = "br.gov.sp.educacao.minhaescola.tituloCompartilhar"
    static let voceTemAlteracoesNaoSalvas = "br.gov.sp.educacao.minhaescola.voceTemAlteracoesNaoSalvas"
}
