devices([
	"iPhone SE",
	"iPhone 5s",
	"iPhone 6",
	"iPhone 6 Plus",
	"iPhone 6s",
	"iPhone 6s Plus",
	"iPhone 7",
	"iPhone 7 Plus",
	"iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPad Pro (12.9-inch) (3rd generation)"
])

scheme("MinhaEscolaSPUITests")

output_directory("./screenshots")